### ISSUE TITLE
3.14 CS版 无法识别小核心

### ISSUE THREAD

**Issue by Fake011130** [CCA2878/Immortalwrt_Xiaomi_AX6s#1]
![屏幕截图 2022-03-14 181021](https://user-images.githubusercontent.com/50409477/158151373-08b59e22-f4f6-46ad-85f5-03180b2f663c.png)

3.14闭源版似乎无法识别小核心，在概况-系统-架构  显示  ？x2
本人是小白，如果表述错误不要介意

**Comment by cca2878** [comment]
应该是不影响使用的~
ARMv8架构比较新，可能会不识别。我这边使用的开源版是识别的~
